### ISSUE TITLE
v3 server won't start with old-style v2 orientdb-server-config.xml 

### ISSUE THREAD

**Issue by athompso** [migibert/orientdb-role#32]
I can't really add anything useful to this: https://github.com/orientechnologies/orientdb/issues/8376

Just got bitten by the same problem.  Some other night, I might fork the repo, figure out how to detect v2/v3 in Ansible, and convert from using templates to the ansible xml_module, or at least to pull in an appropriate set of templates for v2 vs. v3.  But tonight is not that night, sorry.

**Comment by migibert** [comment]
Thanks for opening this issue and sorry for the time you lost for figuring out what was happening, I will take a look in a few days to make sure the role is v3 compatible.
